# Generated by Django 2.0.9 on 2019-01-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='progress',
            field=models.CharField(default='NOT_STARTED', max_length=12),
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
