# Generated by Django 2.0.9 on 2019-01-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='body',
            field=models.TextField(),
        ),
    ]
