# Generated by Django 2.0.9 on 2019-01-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20190109_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='author',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
