# Generated by Django 2.0.9 on 2019-01-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20190109_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='type',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE', 'Feature Request')], default='BUG', max_length=15),
        ),
    ]
