# Generated by Django 2.0.9 on 2019-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20190130_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='type',
            field=models.CharField(choices=[('FEATURE', 'Feature Request'), ('BUG', 'Bug Report')], default='BUG', max_length=15),
        ),
    ]
