# Generated by Django 2.0.9 on 2019-02-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_upvotemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='type',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE', 'Feature Request')], default='BUG', max_length=15),
        ),
    ]
