# Generated by Django 2.0.9 on 2019-02-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20190202_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='type',
            field=models.CharField(choices=[('FEATURE', 'Feature Request'), ('BUG', 'Bug Report')], default='BUG', max_length=15),
        ),
    ]
